### PR TITLE
feat: add deeplinks to guide users into tagging

### LINKED ISSUE #27: Feature: deeplink to Curate for users to submit entries to the registries directly
From what i remember, Curate allows us to deeplink to the submission form of a registry by encoding the form fields in the URL. Perhaps we can do that in the Snap, so that if the data is not present, someone can just click on the deeplink and go directly to Curate to contribute the submission? Though adding it might make the audit more problematic...
@greenlucid

### PR DESCRIPTION
**Pull request by greenlucid**
closes #27
also sanitize strings as #22
also link to projects as #29
refactored code to be more readable

### CODE REVIEW

**Comment by greenlucid** [comment]
@jaybuidl I'm having a linting issue related to dependencies, I added a library `markdown-escape` but eslint complains that it's not added to the "project's dependencies"

**Comment by gmkung** [comment]
@greenlucid just tested it and have a few comments: 
1. Unfortunately links are disallowed in the interface even when the markdown is correct (seems they still only accept [bold and italics](https://docs.metamask.io/guide/snaps-concepts.html#markdown)). The current behaviour is that the text encapsulated by the link just doesn't get displayed. I think we have to just keep the _markdown-escape_ but remove the tags around 'Tag me' for this version :(
Here are screenshots for reference:
image
image
2. About the "Is this a token? [Tag it here]" line, there is two extra spaces that cause the markdown to be recognised, but I think we can better omit this altogether as it will come up for every contract that's not a token and it might be confusing/obstructive to users. Maybe in the future we can use function signatures or something to detect if something is very likely to be a token, we can add this back in?
image
3. About this phrase, 'This contract does **NOT recognize** this domain' - I think it might be confusing as I think it's not the contract that 'recognizes' the domain, but rather that the contract is not known to be used on this domain. Perhaps the phrasing I proposed initially or something else would be better?

**Review by gmkung — APPROVED** [review]
Tested the latest version and all works well and looks good since all the un-renderable links are relegated to the comments.

Some screenshots for reference: 
image
image
image

**Comment by gmkung** [comment]
@jaybuidl could you help with the linting errors?

**Review by jaybuidl — APPROVED** [review]

**Pull request merged**
